"""Seed items: spoken commands whose single negation flips exactly one argument.
Each item: tools (target + distractors), utterance (contains ONE negation cue), neg_span (exact tokens to delete),
gold call, and flipped call (what a transcript-faithful model does after the negation is dropped)."""

def T(name, desc, props, required):
    return {"type": "function", "function": {"name": name, "description": desc,
            "parameters": {"type": "object", "properties": props, "required": required}}}

B = lambda d: {"type": "boolean", "description": d}
S = lambda d, enum=None: ({"type": "string", "description": d, "enum": enum} if enum else {"type": "string", "description": d})
I = lambda d: {"type": "integer", "description": d}

TOOLS = {
 "set_thermostat": T("set_thermostat", "Set the home thermostat.", {"temperature_f": I("Target temperature in Fahrenheit"), "mode": S("Operating mode", ["heat","cool","auto","off"]), "eco": B("Enable eco/energy-saving mode")}, ["temperature_f"]),
 "set_lights": T("set_lights", "Turn lights in a room on or off.", {"room": S("Room name"), "state": S("Desired state", ["on","off"]), "all_rooms": B("Apply to every room in the house")}, ["room","state"]),
 "lock_door": T("lock_door", "Lock or unlock a door.", {"door": S("Door name"), "locked": B("True to lock, false to unlock"), "arm_alarm": B("Also arm the security alarm")}, ["door","locked"]),
 "send_email": T("send_email", "Send an email.", {"to": S("Recipient"), "subject": S("Subject line"), "body": S("Message body"), "cc_manager": B("CC the user's manager"), "mark_urgent": B("Flag the email as urgent")}, ["to","subject"]),
 "schedule_meeting": T("schedule_meeting", "Create a calendar meeting.", {"title": S("Meeting title"), "time": S("Start time, natural language"), "invite_team": B("Invite the whole team"), "send_reminder": B("Send a reminder 15 minutes before"), "video_call": B("Attach a video-call link")}, ["title","time"]),
 "cancel_event": T("cancel_event", "Cancel a calendar event.", {"event": S("Event name or time"), "notify_attendees": B("Notify all attendees about the cancellation")}, ["event"]),
 "place_order": T("place_order", "Order an item from the store.", {"item": S("Item name"), "quantity": I("Number of units"), "express_shipping": B("Use express (next-day) shipping"), "gift_wrap": B("Gift-wrap the order")}, ["item","quantity"]),
 "cancel_order": T("cancel_order", "Cancel an existing order.", {"order_id": S("Order identifier"), "refund_to_card": B("Refund to the original card instead of store credit")}, ["order_id"]),
 "close_project": T("close_project", "Close a project.", {"project_id": S("Project identifier"), "archive": B("Archive the project after closing"), "notify_team": B("Notify team members")}, ["project_id"]),
 "delete_files": T("delete_files", "Delete files in a folder.", {"folder": S("Folder name"), "include_subfolders": B("Also delete files in subfolders"), "keep_backup": B("Keep a backup copy before deleting")}, ["folder"]),
 "transfer_money": T("transfer_money", "Transfer money between accounts.", {"amount_usd": I("Amount in US dollars"), "to_account": S("Destination account"), "recurring_monthly": B("Repeat the transfer every month")}, ["amount_usd","to_account"]),
 "book_flight": T("book_flight", "Book a flight.", {"destination": S("Destination city"), "date": S("Travel date"), "refundable": B("Book a refundable fare"), "window_seat": B("Request a window seat")}, ["destination","date"]),
 "set_alarm": T("set_alarm", "Set an alarm.", {"time": S("Alarm time"), "repeat_weekdays": B("Repeat every weekday"), "vibrate_only": B("Vibrate only, no sound")}, ["time"]),
 "play_music": T("play_music", "Play music.", {"query": S("Artist, album, or playlist"), "shuffle": B("Shuffle playback"), "explicit_allowed": B("Allow explicit tracks")}, ["query"]),
 "share_document": T("share_document", "Share a document with someone.", {"document": S("Document name"), "with_user": S("Person to share with"), "allow_edit": B("Grant edit permission (otherwise view-only)"), "notify": B("Send a notification email")}, ["document","with_user"]),
 "post_message": T("post_message", "Post a message to a chat channel.", {"channel": S("Channel name"), "text": S("Message text"), "notify_everyone": B("Ping everyone in the channel"), "pin": B("Pin the message")}, ["channel","text"]),
 "start_vacuum": T("start_vacuum", "Start the robot vacuum.", {"rooms": S("Comma-separated rooms"), "mop": B("Also mop the floor"), "quiet_mode": B("Run in quiet mode")}, ["rooms"]),
 "set_reminder": T("set_reminder", "Create a reminder.", {"text": S("Reminder text"), "time": S("When to remind"), "repeat_daily": B("Repeat every day")}, ["text","time"]),
 "order_ride": T("order_ride", "Order a ride.", {"pickup": S("Pickup location"), "destination": S("Destination"), "shared": B("Accept a shared/pooled ride"), "child_seat": B("Request a child seat")}, ["pickup","destination"]),
 "update_subscription": T("update_subscription", "Change a subscription.", {"service": S("Service name"), "auto_renew": B("Automatically renew"), "plan": S("Plan tier", ["basic","premium"])}, ["service"]),
 "get_weather": T("get_weather", "Get the weather forecast.", {"city": S("City"), "days": I("Number of days")}, ["city"]),
 "get_stock_price": T("get_stock_price", "Get a stock price.", {"ticker": S("Ticker symbol")}, ["ticker"]),
 "search_recipes": T("search_recipes", "Search recipes.", {"query": S("Dish or ingredient"), "vegetarian": B("Vegetarian only")}, ["query"]),
}

# (id, tools, utterance, neg_span, gold, flipped)  -- utterance is spoken-style, lowercase, numbers as words where natural
ITEMS = [
 ("th1", ["set_thermostat","set_lights","get_weather"], "set the thermostat to seventy two degrees but don't turn on eco mode", "don't", {"set_thermostat": {"temperature_f": 72, "eco": False}}, {"set_thermostat": {"temperature_f": 72, "eco": True}}),
 ("th2", ["set_thermostat","set_alarm"], "put the heat on at sixty eight and no eco mode please", "no", {"set_thermostat": {"temperature_f": 68, "mode": "heat", "eco": False}}, {"set_thermostat": {"temperature_f": 68, "mode": "heat", "eco": True}}),
 ("li1", ["set_lights","lock_door","play_music"], "turn off the lights in the living room but not in the other rooms", "not", {"set_lights": {"room": "living room", "state": "off", "all_rooms": False}}, {"set_lights": {"room": "living room", "state": "off", "all_rooms": True}}),
 ("li2", ["set_lights","start_vacuum"], "switch the kitchen lights on and don't touch the rest of the house", "don't", {"set_lights": {"room": "kitchen", "state": "on", "all_rooms": False}}, {"set_lights": {"room": "kitchen", "state": "on", "all_rooms": True}}),
 ("lo1", ["lock_door","set_lights","set_alarm"], "lock the front door but don't arm the alarm", "don't", {"lock_door": {"door": "front door", "locked": True, "arm_alarm": False}}, {"lock_door": {"door": "front door", "locked": True, "arm_alarm": True}}),
 ("lo2", ["lock_door","set_thermostat"], "lock the garage door and no alarm tonight", "no", {"lock_door": {"door": "garage door", "locked": True, "arm_alarm": False}}, {"lock_door": {"door": "garage door", "locked": True, "arm_alarm": True}}),
 ("em1", ["send_email","post_message","schedule_meeting"], "email sarah that the report is ready but don't cc my manager", "don't", {"send_email": {"to": "sarah", "subject": "report is ready", "cc_manager": False}}, {"send_email": {"to": "sarah", "subject": "report is ready", "cc_manager": True}}),
 ("em2", ["send_email","share_document"], "send tom an email saying the meeting moved to friday and do not mark it urgent", "not", {"send_email": {"to": "tom", "subject": "meeting moved to friday", "mark_urgent": False}}, {"send_email": {"to": "tom", "subject": "meeting moved to friday", "mark_urgent": True}}),
 ("em3", ["send_email","cancel_event"], "write to the vendor about the invoice with no cc to my manager", "no", {"send_email": {"to": "vendor", "subject": "invoice", "cc_manager": False}}, {"send_email": {"to": "vendor", "subject": "invoice", "cc_manager": True}}),
 ("me1", ["schedule_meeting","cancel_event","send_email"], "schedule a budget review tomorrow at ten but don't invite the whole team", "don't", {"schedule_meeting": {"title": "budget review", "time": "tomorrow at 10", "invite_team": False}}, {"schedule_meeting": {"title": "budget review", "time": "tomorrow at 10", "invite_team": True}}),
 ("me2", ["schedule_meeting","set_reminder"], "set up a design sync at three with no reminder", "no", {"schedule_meeting": {"title": "design sync", "time": "3", "send_reminder": False}}, {"schedule_meeting": {"title": "design sync", "time": "3", "send_reminder": True}}),
 ("me3", ["schedule_meeting","order_ride"], "book a one on one with priya on monday at nine and don't add a video link", "don't", {"schedule_meeting": {"title": "one on one with priya", "time": "monday at 9", "video_call": False}}, {"schedule_meeting": {"title": "one on one with priya", "time": "monday at 9", "video_call": True}}),
 ("ce1", ["cancel_event","schedule_meeting","send_email"], "cancel the four o'clock standup but don't notify the attendees", "don't", {"cancel_event": {"event": "4 o'clock standup", "notify_attendees": False}}, {"cancel_event": {"event": "4 o'clock standup", "notify_attendees": True}}),
 ("ce2", ["cancel_event","cancel_order"], "cancel the dentist appointment tomorrow without notifying anyone", "without", {"cancel_event": {"event": "tomorrow's dentist appointment", "notify_attendees": False}}, {"cancel_event": {"event": "tomorrow's dentist appointment", "notify_attendees": True}}),
 ("or1", ["place_order","cancel_order","search_recipes"], "order two boxes of printer paper but not with express shipping", "not", {"place_order": {"item": "printer paper", "quantity": 2, "express_shipping": False}}, {"place_order": {"item": "printer paper", "quantity": 2, "express_shipping": True}}),
 ("or2", ["place_order","get_stock_price"], "get me one bag of coffee beans and no gift wrap", "no", {"place_order": {"item": "coffee beans", "quantity": 1, "gift_wrap": False}}, {"place_order": {"item": "coffee beans", "quantity": 1, "gift_wrap": True}}),
 ("or3", ["place_order","order_ride"], "buy three phone chargers and don't use express delivery", "don't", {"place_order": {"item": "phone chargers", "quantity": 3, "express_shipping": False}}, {"place_order": {"item": "phone chargers", "quantity": 3, "express_shipping": True}}),
 ("co1", ["cancel_order","place_order","transfer_money"], "cancel order a b one two three but don't refund it to my card", "don't", {"cancel_order": {"order_id": "AB123", "refund_to_card": False}}, {"cancel_order": {"order_id": "AB123", "refund_to_card": True}}),
 ("co2", ["cancel_order","update_subscription"], "cancel order number nine nine four and no refund to the card i want store credit", "no", {"cancel_order": {"order_id": "994", "refund_to_card": False}}, {"cancel_order": {"order_id": "994", "refund_to_card": True}}),
 ("cp1", ["close_project","delete_files","post_message"], "close the alpha project d a twelve but do not archive it", "not", {"close_project": {"project_id": "DA12", "archive": False}}, {"close_project": {"project_id": "DA12", "archive": True}}),
 ("cp2", ["close_project","share_document"], "close the alpha project and don't notify the team", "don't", {"close_project": {"project_id": "alpha", "notify_team": False}}, {"close_project": {"project_id": "alpha", "notify_team": True}}),
 ("df1", ["delete_files","close_project","share_document"], "delete the files in the downloads folder but not the subfolders", "not", {"delete_files": {"folder": "downloads", "include_subfolders": False}}, {"delete_files": {"folder": "downloads", "include_subfolders": True}}),
 ("df2", ["delete_files","start_vacuum"], "clear out the temp folder and don't keep a backup", "don't", {"delete_files": {"folder": "temp", "keep_backup": False}}, {"delete_files": {"folder": "temp", "keep_backup": True}}),
 ("tr1", ["transfer_money","get_stock_price","cancel_order"], "transfer three hundred dollars to my savings account but don't make it recurring", "don't", {"transfer_money": {"amount_usd": 300, "to_account": "savings", "recurring_monthly": False}}, {"transfer_money": {"amount_usd": 300, "to_account": "savings", "recurring_monthly": True}}),
 ("tr2", ["transfer_money","update_subscription"], "send fifty dollars to mom's account with no monthly repeat", "no", {"transfer_money": {"amount_usd": 50, "to_account": "mom", "recurring_monthly": False}}, {"transfer_money": {"amount_usd": 50, "to_account": "mom", "recurring_monthly": True}}),
 ("bf1", ["book_flight","order_ride","get_weather"], "book me a flight to denver on the twelfth but not a refundable one", "not", {"book_flight": {"destination": "denver", "date": "the 12th", "refundable": False}}, {"book_flight": {"destination": "denver", "date": "the 12th", "refundable": True}}),
 ("bf2", ["book_flight","set_reminder"], "get a flight to boston next tuesday and don't request a window seat", "don't", {"book_flight": {"destination": "boston", "date": "next tuesday", "window_seat": False}}, {"book_flight": {"destination": "boston", "date": "next tuesday", "window_seat": True}}),
 ("al1", ["set_alarm","set_reminder","play_music"], "set an alarm for six thirty but don't repeat it on weekdays", "don't", {"set_alarm": {"time": "6:30", "repeat_weekdays": False}}, {"set_alarm": {"time": "6:30", "repeat_weekdays": True}}),
 ("al2", ["set_alarm","set_thermostat"], "wake me at seven and no vibrate only mode i want sound", "no", {"set_alarm": {"time": "7", "vibrate_only": False}}, {"set_alarm": {"time": "7", "vibrate_only": True}}),
 ("pm1", ["play_music","set_lights","search_recipes"], "play some taylor swift but don't shuffle", "don't", {"play_music": {"query": "taylor swift", "shuffle": False}}, {"play_music": {"query": "taylor swift", "shuffle": True}}),
 ("pm2", ["play_music","set_alarm"], "put on the workout playlist and no explicit songs the kids are here", "no", {"play_music": {"query": "workout playlist", "explicit_allowed": False}}, {"play_music": {"query": "workout playlist", "explicit_allowed": True}}),
 ("sd1", ["share_document","send_email","post_message"], "share the budget spreadsheet with alex but don't give edit access", "don't", {"share_document": {"document": "budget spreadsheet", "with_user": "alex", "allow_edit": False}}, {"share_document": {"document": "budget spreadsheet", "with_user": "alex", "allow_edit": True}}),
 ("sd2", ["share_document","close_project"], "share the roadmap doc with jordan without sending a notification", "without", {"share_document": {"document": "roadmap doc", "with_user": "jordan", "notify": False}}, {"share_document": {"document": "roadmap doc", "with_user": "jordan", "notify": True}}),
 ("po1", ["post_message","send_email","schedule_meeting"], "post in the general channel that lunch is at noon but don't ping everyone", "don't", {"post_message": {"channel": "general", "text": "lunch is at noon", "notify_everyone": False}}, {"post_message": {"channel": "general", "text": "lunch is at noon", "notify_everyone": True}}),
 ("po2", ["post_message","share_document"], "tell the dev channel the build is green and do not pin it", "not", {"post_message": {"channel": "dev", "text": "the build is green", "pin": False}}, {"post_message": {"channel": "dev", "text": "the build is green", "pin": True}}),
 ("va1", ["start_vacuum","set_lights","delete_files"], "vacuum the kitchen and hallway but don't mop", "don't", {"start_vacuum": {"rooms": "kitchen, hallway", "mop": False}}, {"start_vacuum": {"rooms": "kitchen, hallway", "mop": True}}),
 ("va2", ["start_vacuum","set_thermostat"], "run the vacuum in the bedroom with no quiet mode", "no", {"start_vacuum": {"rooms": "bedroom", "quiet_mode": False}}, {"start_vacuum": {"rooms": "bedroom", "quiet_mode": True}}),
 ("re1", ["set_reminder","set_alarm","schedule_meeting"], "remind me to call the bank at two but not every day just once", "not", {"set_reminder": {"text": "call the bank", "time": "2", "repeat_daily": False}}, {"set_reminder": {"text": "call the bank", "time": "2", "repeat_daily": True}}),
 ("ri1", ["order_ride","book_flight","get_weather"], "get me a ride from the office to the airport but not a shared one", "not", {"order_ride": {"pickup": "office", "destination": "airport", "shared": False}}, {"order_ride": {"pickup": "office", "destination": "airport", "shared": True}}),
 ("ri2", ["order_ride","place_order"], "order a car from home to the station and don't add a child seat", "don't", {"order_ride": {"pickup": "home", "destination": "station", "child_seat": False}}, {"order_ride": {"pickup": "home", "destination": "station", "child_seat": True}}),
 ("su1", ["update_subscription","cancel_order","transfer_money"], "keep my music subscription on the basic plan but don't auto renew it", "don't", {"update_subscription": {"service": "music", "plan": "basic", "auto_renew": False}}, {"update_subscription": {"service": "music", "plan": "basic", "auto_renew": True}}),
 ("su2", ["update_subscription","play_music"], "switch the news subscription to premium with no automatic renewal", "no", {"update_subscription": {"service": "news", "plan": "premium", "auto_renew": False}}, {"update_subscription": {"service": "news", "plan": "premium", "auto_renew": True}}),
]

# Bystander speech pool (other speaker in the room). 'intent' fragments name a valid action for some tool; 'chatter' has no action.
BYSTANDER_INTENT = [
 "turn off the kitchen lights", "set it to seventy eight", "cancel the meeting at four", "order two more of those",
 "lock the back door", "play the beatles", "send it to everyone", "make it urgent", "book the flight for saturday",
 "delete the old photos too", "transfer a hundred to checking", "set an alarm for five", "share it with the whole team",
 "archive it", "notify the team", "shuffle it", "get express shipping", "pin that message",
]
BYSTANDER_1W = ["delete", "cancel", "everyone", "urgent", "archive", "shuffle", "lock", "unlock", "tomorrow", "premium", "express", "notify", "stop", "all", "kitchen", "friday"]
BYSTANDER_CHATTER = [
 "i'll be home by six", "the game starts at eight", "did you feed the dog", "it's raining again",
 "pass me the remote", "grandma called earlier", "we're out of milk", "the kids are upstairs",
 "traffic was awful today", "that movie was so long", "what time is dinner", "my phone is at two percent",
]
# near-homophone / plausible-misrecognition substitutions for content words (key -> replacement)
CONTENT_SUB = {
 "seventy": "seventeen", "sixty": "sixteen", "living": "dining", "kitchen": "bedroom", "front": "back", "garage": "garden",
 "sarah": "sara", "tom": "tim", "vendor": "lender", "budget": "budgets", "friday": "monday", "priya": "maria",
 "monday": "sunday", "standup": "standoff", "dentist": "dennis", "paper": "pepper", "coffee": "toffee", "chargers": "charges",
 "three": "free", "two": "ten", "nine": "five", "alpha": "alfa", "twelve": "twenty", "tomorrow": "marrow", "appointment": "apartment", "downloads": "uploads", "temp": "tent", "savings": "checking",
 "mom's": "tom's", "denver": "dover", "boston": "austin", "six": "sixth", "seven": "eleven", "taylor": "tyler",
 "workout": "walkout", "alex": "alec", "jordan": "gordon", "general": "journal", "dev": "death", "hallway": "hall",
 "bedroom": "bathroom", "bank": "bang", "office": "orifice", "airport": "airpod", "home": "hume", "station": "stadium",
 "music": "muse", "news": "views", "fifty": "fifteen", "hundred": "hundreds", "twelfth": "twentieth", "tuesday": "thursday",
 "thirty": "thirteen", "one": "won", "report": "rapport", "invoice": "invoices", "design": "designs", "review": "revue",
}
FUNCTION_WORDS = ["the","a","an","to","for","me","please","and","it","my","some","in","on","of","up","with"]

# Positive mirrors (P0c): the optional boolean is genuinely wanted; gold = the negated card's flipped call
POS_UTTERANCES = {'th1': 'set the thermostat to seventy two degrees and turn on eco mode', 'th2': 'put the heat on at sixty eight with eco mode please', 'li1': 'turn off the lights in the living room and in all the other rooms too', 'li2': 'switch the kitchen lights on and do the rest of the house as well', 'lo1': 'lock the front door and arm the alarm', 'lo2': 'lock the garage door and set the alarm tonight', 'em1': 'email sarah that the report is ready and cc my manager', 'em2': 'send tom an email saying the meeting moved to friday and mark it urgent', 'em3': 'write to the vendor about the invoice with a cc to my manager', 'me1': 'schedule a budget review tomorrow at ten and invite the whole team', 'me2': 'set up a design sync at three with a reminder', 'me3': 'book a one on one with priya on monday at nine and add a video link', 'ce1': "cancel the four o'clock standup and notify the attendees", 'ce2': 'cancel the dentist appointment tomorrow and notify everyone', 'or1': 'order two boxes of printer paper with express shipping', 'or2': 'get me one bag of coffee beans with gift wrap', 'or3': 'buy three phone chargers and use express delivery', 'co1': 'cancel order a b one two three and refund it to my card', 'co2': 'cancel order number nine nine four and refund it to the card', 'cp1': 'close the alpha project d a twelve and archive it', 'cp2': 'close the alpha project and notify the team', 'df1': 'delete the files in the downloads folder including the subfolders', 'df2': 'clear out the temp folder and keep a backup', 'tr1': 'transfer three hundred dollars to my savings account and make it recurring', 'tr2': "send fifty dollars to mom's account with a monthly repeat", 'bf1': 'book me a flight to denver on the twelfth and make it refundable', 'bf2': 'get a flight to boston next tuesday and request a window seat', 'al1': 'set an alarm for six thirty and repeat it on weekdays', 'al2': 'wake me at seven in vibrate only mode', 'pm1': 'play some taylor swift on shuffle', 'pm2': 'put on the workout playlist and allow explicit songs', 'sd1': 'share the budget spreadsheet with alex and give edit access', 'sd2': 'share the roadmap doc with jordan and send a notification', 'po1': 'post in the general channel that lunch is at noon and ping everyone', 'po2': 'tell the dev channel the build is green and pin it', 'va1': 'vacuum the kitchen and hallway and mop too', 'va2': 'run the vacuum in the bedroom in quiet mode', 're1': 'remind me to call the bank at two every day', 'ri1': 'get me a shared ride from the office to the airport', 'ri2': 'order a car from home to the station and add a child seat', 'su1': 'keep my music subscription on the basic plan and auto renew it', 'su2': 'switch the news subscription to premium with automatic renewal'}
